# Generated by Django 5.0.2 on 2024-02-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('nombre_padre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_padre', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_madre', models.CharField(blank=True, max_length=20, null=True)),
                ('nro_contacto', models.CharField(blank=True, max_length=15, null=True)),
            ],
            bases=('persona.persona',),
        ),
    ]
