# Generated by Django 5.0.2 on 2024-02-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('persona', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuela.escuela'),
        ),
    ]
