# Generated by Django 5.0.2 on 2024-03-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones', to='supervision.supervision'),
        ),
    ]
